name: getx_example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  fetchly: ^0.0.1
  flutter:
    sdk: flutter
  get: ^5.0.0-release-candidate-4
  lazyui: ^1.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
